Proper commit message scan

diff --git a/.github/workflows/get_real_pr_shas.yml b/.github/workflows/get_real_pr_shas.yml
--- a/.github/workflows/get_real_pr_shas.yml
+++ b/.github/workflows/get_real_pr_shas.yml
@@ -29,6 +29,7 @@
 #
 # Use `${{ needs.real_pr_shas.outputs.BASE_SHA }}` to get the real base sha.
 # Use `${{ needs.real_pr_shas.outputs.HEAD_SHA }}` to get the PR head commit sha.
+# Use `${{ needs.real_pr_shas.outputs.COMMIT_MSGS }}` to get the commit messages of git log --pretty=%B BASE_SHA..HEAD_SHA
 #
 # This workflow is copied from https://github.com/JensDll/should-run/blob/main/.github/workflows/main.yaml#L54
 #
@@ -47,6 +48,9 @@ on:
       HEAD_SHA:
         description: "The real PR commit HEAD sha"
         value: ${{ jobs.get_real_pr_shas.outputs.output_head }}
+      COMMIT_MSGS:
+        description: "The commit messages of BASE_SHA..HEAD_SHA"
+        value: ${{ jobs.get_real_pr_shas.outputs.output_msgs }}
 
 jobs:
   get_real_pr_shas:
@@ -54,6 +58,7 @@ jobs:
     outputs:
       output_base: ${{ steps.get_shas.outputs.BASE_SHA }}
       output_head: ${{ steps.get_shas.outputs.HEAD_SHA }}
+      output_head: ${{ steps.get_shas.outputs.COMMI_MSGS }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -68,10 +73,18 @@ jobs:
             git fetch --no-tags --prune --no-recurse-submodules --deepen=10 origin ${{ github.event.pull_request.base.sha }}
           done
 
-          base=$(git rev-list ${{ github.event.pull_request.head.sha }} ^${{ github.event.pull_request.base.sha }} | tail --lines 1 | xargs -I {} git rev-parse {}~1)
+          BASE_SHA=$(git rev-list ${{ github.event.pull_request.head.sha }} ^${{ github.event.pull_request.base.sha }} | tail --lines 1 | xargs -I {} git rev-parse {}~1)
+          HEAD_SHA=${{ github.event.pull_request.head.sha }}
+          COMMIT_MSGS=$(git log --pretty=%B "$BASE_SHA".."$HEAD_SHA")
+          if [[ $? -eq 128 ]]; then
+          	echo "Failed to get log"
+          	exit 2
+          fi
 
-          echo "BASE_SHA=$base"
-          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}"
+          echo "BASE_SHA=$BASE_SHA"
+          echo "HEAD_SHA=$HEAD_SHA"
+          echo -e "COMMIT_MSGS:\n$COMMIT_MSGS"
 
-          echo "BASE_SHA=$base" >> $GITHUB_OUTPUT
-          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
+          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_OUTPUT
+          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_OUTPUT
+          echo "COMMIT_MSGS=$COMMIT_MSGS" >> $GITHUB_OUTPUT
